[package]
name = "xdrgen"
version = "0.1.0"
authors = ["Kyle Bartush <kbartush@kochava.com>"]
edition = "2018"

[dependencies]
mazzaroth-xdr = { git = "ssh://git@github.com/kochavalabs/mazzaroth-xdr.git", branch = "kv-query" }
ex-dee = { git = "ssh://git@github.com/kochavalabs/ex-dee.git" }
pest = "2.1.1"
pest_derive = "2.1.0"
structopt = "0.2.15"
handlebars = "1.1.0"
serde = "1.0.90"
serde_derive = "1.0.90"
