version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt -- --check
      - run:
          name: Stable Build
          command: |
            rustup toolchain install stable
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Test
          command: |
            rustup toolchain install stable
            rustup run stable cargo test
      - run:
          name: Generate Files
          command: |
            cargo run test.x --language js
            cargo run test.x --language rust
            cargo run test.x --language go
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build